routes/web.php
<?php

use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\URL;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

if (App::environment('production')) {
    URL::forceScheme('https');
}

Route::get('/', 'Auth\LoginController@showLoginOrRegister')->name('login');

Auth::routes();

Route::get('/invitations/accept/{key}', 'SettingsController@acceptInvitation');
Route::post('/invitations/accept/{key}', 'SettingsController@storeAcceptedInvitation')->name('invitations.accept');

Route::middleware(['auth'])->group(function () {
    Route::get('/logout', 'Auth\LoginController@logout');
});

Route::middleware(['auth', '2fa'])->group(function () {
    Route::post('/validate2fa', 'Auth\Validate2faController@index');
});

Route::middleware(['auth', 'auth.confirm', 'u2f', '2fa'])->group(function () {
    Route::name('dashboard.')->group(function () {
        Route::get('/dashboard', 'DashboardController@index')->name('index');
        Route::get('/dashboard/calls', 'DashboardController@calls');
        Route::get('/dashboard/notes', 'DashboardController@notes');
        Route::get('/dashboard/debts', 'DashboardController@debts');
        Route::get('/dashboard/tasks', 'DashboardController@tasks');
        Route::post('/dashboard/setTab', 'DashboardController@setTab');
    });

    Route::get('/compliance', 'ComplianceController@index')->name('compliance');
    Route::post('/compliance/sign', 'ComplianceController@store');
    Route::get('/changelog', 'ChangelogController@index')->name('changelog.index');

    Route::name('people.')->group(function () {
        Route::get('/people', 'ContactsController@index')->name('index');
        Route::get('/people/add', 'ContactsController@create')->name('create');
        Route::get('/people/notfound', 'ContactsController@missing')->name('missing');
        Route::post('/people', 'ContactsController@store')->name('store');

        // Dashboard
        Route::get('/people/{contact}', 'ContactsController@show')->name('show');
        Route::get('/people/{contact}/edit', 'ContactsController@edit')->name('edit');
        Route::post('/people/{contact}/update', 'ContactsController@update')->name('update');
        Route::delete('/people/{contact}', 'ContactsController@delete')->name('delete');

        // Life events
        Route::name('lifeevent.')->group(function () {
            Route::get('/people/{contact}/lifeevents', 'Contacts\\LifeEventsController@index')->name('index');
            Route::get('/lifeevents/categories', 'Contacts\\LifeEventsController@categories')->name('categories');
            Route::get('/lifeevents/categories/{lifeEventCategory}/types', 'Contacts\\LifeEventsController@types')->name('types');
            Route::post('/people/{contact}/lifeevents', 'Contacts\\LifeEventsController@store')->name('store');
            Route::delete('/lifeevents/{lifeevent}', 'Contacts\\LifeEventsController@destroy')->name('destroy');
        });

        // Contact information
        Route::get('/people/{contact}/contactfield', 'Contacts\\ContactFieldsController@getContactFields');
        Route::post('/people/{contact}/contactfield', 'Contacts\\ContactFieldsController@storeContactField');
        Route::put('/people/{contact}/contactfield/{contact_field}', 'Contacts\\ContactFieldsController@editContactField');
        Route::delete('/people/{contact}/contactfield/{contact_field}', 'Contacts\\ContactFieldsController@destroyContactField');
        Route::get('/people/{contact}/contactfieldtypes', 'Contacts\\ContactFieldsController@getContactFieldTypes');

        // Export as vCard
        Route::get('/people/{contact}/vcard', 'ContactsController@vcard')->name('vcard');

        // Addresses
        Route::get('/countries', 'Contacts\\AddressesController@getCountries');
        Route::get('/people/{contact}/addresses', 'Contacts\\AddressesController@get');
        Route::post('/people/{contact}/addresses', 'Contacts\\AddressesController@store');
        Route::put('/people/{contact}/addresses/{address}', 'Contacts\\AddressesController@edit');
        Route::delete('/people/{contact}/addresses/{address}', 'Contacts\\AddressesController@destroy');

        // Work information
        Route::name('work.')->group(function () {
            Route::get('/people/{contact}/work/edit', 'ContactsController@editWork')->name('edit');
            Route::post('/people/{contact}/work/update', 'ContactsController@updateWork')->name('update');
        });

        // Introductions
        Route::name('introductions.')->group(function () {
            Route::get('/people/{contact}/introductions/edit', 'Contacts\\IntroductionsController@edit')->name('edit');
            Route::post('/people/{contact}/introductions/update', 'Contacts\\IntroductionsController@update')->name('update');
        });

        // Tags
        Route::name('tags.')->group(function () {
            Route::post('/people/{contact}/tags/update', 'Contacts\\TagsController@update')->name('update');
        });

        // Notes
        Route::name('notes.')->group(function () {
            Route::get('/people/{contact}/notes', 'Contacts\\NotesController@get');
            Route::post('/people/{contact}/notes', 'Contacts\\NotesController@store')->name('store');
            Route::put('/people/{contact}/notes/{note}', 'Contacts\\NotesController@update');
            Route::delete('/people/{contact}/notes/{note}', 'Contacts\\NotesController@destroy');
            Route::post('/people/{contact}/notes/{note}/toggle', 'Contacts\\NotesController@toggle');
        });

        // Food preferencies
        Route::name('food.')->group(function () {
            Route::get('/people/{contact}/food', 'ContactsController@editFoodPreferencies')->name('index');
            Route::post('/people/{contact}/food/save', 'ContactsController@updateFoodPreferencies')->name('update');
        });

        // Relationships
        Route::name('relationships.')->group(function () {
            Route::get('/people/{contact}/relationships/new', 'Contacts\\RelationshipsController@new')->name('create');
            Route::post('/people/{contact}/relationships/store', 'Contacts\\RelationshipsController@store')->name('store');
            Route::get('/people/{contact}/relationships/{otherContact}/edit', 'Contacts\\RelationshipsController@edit')->name('edit');
            Route::post('/people/{contact}/relationships/{otherContact}', 'Contacts\\RelationshipsController@update')->name('update');
            Route::delete('/people/{contact}/relationships/{otherContact}', 'Contacts\\RelationshipsController@destroy')->name('delete');
        });

        // Pets
        Route::name('pets.')->group(function () {
            Route::get('/people/{contact}/pets', 'Contacts\\PetsController@get')->name('index');
            Route::post('/people/{contact}/pet', 'Contacts\\PetsController@store')->name('store');
            Route::put('/people/{contact}/pet/{pet}', 'Contacts\\PetsController@update')->name('update');
            Route::delete('/people/{contact}/pet/{pet}', 'Contacts\\PetsController@trash')->name('delete');
            Route::get('/petcategories', 'Contacts\\PetsController@getPetCategories');
        });

        // Reminders
        Route::name('reminders.')->group(function () {
            Route::get('/people/{contact}/reminders/add', 'Contacts\\RemindersController@create')->name('add');
            Route::post('/people/{contact}/reminders/store', 'Contacts\\RemindersController@store')->name('store');
            Route::get('/people/{contact}/reminders/{reminder}/edit', 'Contacts\\RemindersController@edit')->name('edit');
            Route::put('/people/{contact}/reminders/{reminder}', 'Contacts\\RemindersController@update')->name('update');
            Route::delete('/people/{contact}/reminders/{reminder}', 'Contacts\\RemindersController@destroy')->name('delete');
        });

        // Tasks
        Route::name('tasks.')->group(function () {
            Route::get('/people/{contact}/tasks', 'Contacts\\TasksController@get')->name('index');
            Route::post('/people/{contact}/tasks', 'Contacts\\TasksController@store')->name('store');
            Route::post('/people/{contact}/tasks/{task}/toggle', 'Contacts\\TasksController@toggle');
            Route::put('/people/{contact}/tasks/{task}', 'Contacts\\TasksController@update')->name('update');
            Route::delete('/people/{contact}/tasks/{task}', 'Contacts\\TasksController@destroy')->name('delete');
        });

        // Gifts
        Route::name('gifts.')->group(function () {
            Route::get('/people/{contact}/gifts', 'Contacts\\GiftsController@get')->name('index');
            Route::post('/people/{contact}/gifts/{gift}/toggle', 'Contacts\\GiftsController@toggle');
            Route::get('/people/{contact}/gifts/add', 'Contacts\\GiftsController@create')->name('add');
            Route::get('/people/{contact}/gifts/{gift}/edit', 'Contacts\\GiftsController@edit')->name('edit');
            Route::post('/people/{contact}/gifts/store', 'Contacts\\GiftsController@store')->name('store');
            Route::post('/people/{contact}/gifts/{gift}/update', 'Contacts\\GiftsController@update')->name('update');
            Route::delete('/people/{contact}/gifts/{gift}', 'Contacts\\GiftsController@destroy')->name('delete');
        });

        // Debt
        Route::name('debt.')->group(function () {
            Route::get('/people/{contact}/debt/add', 'Contacts\\DebtController@create')->name('add');

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use App\Models\User\User;
use App\Helpers\DateHelper;
use App\Models\Contact\Debt;
use Illuminate\Http\Request;
use App\Models\Contact\Contact;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\Auth;
use App\Http\Resources\Debt\Debt as DebtResource;
use App\Http\Resources\Task\Task as TaskResource;

class DashboardController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $account = auth()->user()->account()
            ->withCount(
                'contacts', 'reminders', 'notes', 'activities', 'gifts', 'tasks'
            )->with('debts.contact')
            ->first();

        if ($account->contacts()->count() === 0) {
            return view('dashboard.blank');
        }

        // Fetch last updated contacts
        $lastUpdatedContactsCollection = collect([]);
        $lastUpdatedContacts = $account->contacts()->where('is_partial', false)->latest('updated_at')->limit(10)->get();
        foreach ($lastUpdatedContacts as $contact) {
            $data = [
                'id' => $contact->hashID(),
                'has_avatar' => $contact->has_avatar,
                'avatar_url' => $contact->getAvatarURL(110),
                'initials' => $contact->getInitials(),
                'default_avatar_color' => $contact->default_avatar_color,
                'complete_name' => $contact->name,
            ];
            $lastUpdatedContactsCollection->push(json_encode($data));
        }

        $debt = $account->debts->where('status', 'inprogress');

        $debt_due = $debt->where('in_debt', 'yes')
            ->reduce(function ($totalDueDebt, Debt $debt) {
                return $totalDueDebt + $debt->amount;
            }, 0);

        $debt_owed = $debt->where('in_debt', 'no')
            ->reduce(function ($totalOwedDebt, Debt $debt) {
                return $totalOwedDebt + $debt->amount;
            }, 0);

        $data = [
            'lastUpdatedContacts' => $lastUpdatedContactsCollection,
            'number_of_contacts' => $account->contacts()->real()->count(),
            'number_of_reminders' => $account->reminders_count,
            'number_of_notes' => $account->notes_count,
            'number_of_activities' => $account->activities_count,
            'number_of_gifts' => $account->gifts_count,
            'number_of_tasks' => $account->tasks_count,
            'debt_due' => $debt_due,
            'debt_owed' => $debt_owed,
            'debts' => $debt,
            'user' => auth()->user(),
        ];

        return view('dashboard.index', $data);
    }

    /**
     * Get calls for the dashboard.
     * @return Collection
     */
    public function calls()
    {
        $callsCollection = collect([]);
        $calls = auth()->user()->account->calls()->limit(15)->get();

        foreach ($calls as $call) {
            $data = [
                'id' => $call->id,
                'called_at' => DateHelper::getShortDate($call->called_at),
                'name' => $call->contact->getIncompleteName(),
                'contact_id' => $call->contact->hashID(),
            ];
            $callsCollection->push($data);
        }

        return $callsCollection;
    }

    /**
     * Get notes for the dashboard.
     * @return Collection
     */
    public function notes()
    {
        $notesCollection = collect([]);
        $notes = auth()->user()->account->notes()->favorited()->get();

        foreach ($notes as $note) {
            $data = [
                'id' => $note->id,
                'body' => $note->body,
                'created_at' => DateHelper::getShortDate($note->created_at),
                'name' => $note->contact->getIncompleteName(),
                'contact' => [
                    'id' => $note->contact->hashID(),
                    'has_avatar' => $note->contact->has_avatar,
                    'avatar_url' => $note->contact->getAvatarURL(110),
                    'initials' => $note->contact->getInitials(),
                    'default_avatar_color' => $note->contact->default_avatar_color,
                    'complete_name' => $note->contact->name,
                ],
            ];
            $notesCollection->push($data);
        }

        return $notesCollection;
    }

    /**
     * Get debts for the dashboard.
     * @return Collection
     */
    public function debts()
    {
        $debtsCollection = collect([]);
        $debts = auth()->user()->account->debts()->get();

        foreach ($debts as $debt) {
            $debtsCollection->push(new DebtResource($debt));
        }

        return $debtsCollection;
    }

    /**
     * Get tasks for the dashboard.
     *
     * @return Collection
     */
    public function tasks()
    {
        $tasksCollection = collect([]);
        $tasks = auth()->user()->account->tasks()->where('completed', 0)->get();

        foreach ($tasks as $task) {
            $tasksCollection->push(new TaskResource($task));
        }

        return $tasksCollection;
    }

    /**
     * Save the current active tab to the User table.
     */
    public function setTab(Request $request)
    {
        auth()->user()->dashboard_active_tab = $request->get('tab');
        auth()->user()->save();
    }
}

resources/views/dashboard/_monthReminder.blade.php
<h3 class="ttu fw5 f5 pb2">{{ \App\Helpers\DateHelper::getMonthAndYear($month) }}</h3>
<ul class="mb4">
  @if (count(auth()->user()->account->getRemindersForMonth($month)) > 0)
    @foreach (auth()->user()->account->getRemindersForMonth($month) as $reminder)
    <li class="pb2">
      <span class="ttu f6 mr2 black-60">{{ \App\Helpers\DateHelper::getShortDateWithoutYear($reminder->next_expected_date) }}</span>
      <span>

        @if ($reminder->contact->is_partial)

        <a href="{{ route('people.show', $reminder->contact->getRelatedRealContact()) }}">{{ $reminder->contact->getRelatedRealContact()->getIncompleteName() }}</a>

        @else

        <a href="{{ route('people.show', $reminder->contact) }}">{{ $reminder->contact->getIncompleteName() }}</a>

        @endif
      </span>
      {{ $reminder->title }}
    </li>
    @endforeach
  @else
  <p>{{ trans('dashboard.reminders_none') }}</p>
  @endif
</ul>

resources/views/dashboard/blank.blade.php
@extends('layouts.skeleton')

@section('content')

  <div class="mw6 center mt5 mt6-ns mb4 ph3 ph0-ns">
    <div class="tc mb5">
      <img src="/img/dashboard/blank.svg">
    </div>
    <h2 class="f2 mb4 normal tc lh-title">{{ trans('dashboard.dashboard_blank_title') }}</h2>
    <p class="tc f4 mb4">{{ trans('dashboard.dashboard_blank_description') }}</p>
    <p class="tc mb5"><a href="{{ route('people.create') }}" id="button-add-contact" class="btn btn-primary pa4 f4">{{ trans('dashboard.dashboard_blank_cta') }}</a></p>
  </div>

@endsection

resources/views/dashboard/index.blade.php
@extends('layouts.skeleton')

@section('content')
  <div class="dashboard">

    <section class="ph3 ph5-ns pv4 cf w-100 bg-gray-monica">
      <div class="mw9 center">
        <div class="{{ htmldir() == 'ltr' ? 'fl' : 'fr' }} w-70 ph2">
          <div class="flex items-center">
            <div class="pr2">
              {{ trans('people.people_list_last_updated') }}
            </div>
            @foreach($lastUpdatedContacts as $contact)
            <div class="pr2 pointer avatars">
              <avatar v-bind:contact="{{ $contact }}" v-bind:clickable="true"></avatar>
            </div>
            @endforeach
          </div>
        </div>
        <div class="{{ htmldir() == 'ltr' ? 'fl tr' : 'fr tl' }} w-30 ph2">
          <a href="{{ route('people.create') }}" class="btn btn-primary" style="padding: 15px 45px;">
            {{ trans('people.people_list_blank_cta') }}
          </a>
        </div>
      </div>
    </section>

    {{-- Main section --}}
    <section class="ph3 ph5-ns cf w-100 bg-gray-monica">
      <div class="mw9 center">
        <div class="{{ htmldir() == 'ltr' ? 'fl' : 'fr' }} w-50-ns w-100 pa2">
          <div class="br3 ba b--gray-monica bg-white mb4">
            <div class="pa3 bb b--gray-monica">
              <p class="mb0">
                <img src="/img/people/reminders.svg" width="17">
                {{ trans('dashboard.reminders_next_months') }}
              </p>
            </div>
            <div class="pt3 pr3 pl3 mb4">
              {{-- Current month --}}
              @include('dashboard._monthReminder', ['month' => 0])

              {{-- Current month + 1 --}}
              @include('dashboard._monthReminder', ['month' => 1])

              {{-- Current month + 2 --}}
              @include('dashboard._monthReminder', ['month' => 2])
            </div>
          </div>
        </div>
        <div class="{{ htmldir() == 'ltr' ? 'fl' : 'fr' }} w-50-ns w-100 pa2">
          <div class="br3 ba b--gray-monica bg-white mb3">
            <div class="pa3 bb b--gray-monica tc">
              <ul>
                <li class="tc dib mr5">
                  <span class="db f3 fw5 green">{{ $number_of_contacts }}</span>
                  <span class="stat-description">{{ trans('dashboard.statistics_contacts') }}</span>
                </li>
                <li class="tc dib mr5">
                  <span class="db f3 fw5 blue">{{ $number_of_activities }}</span>
                  <span class="stat-description">{{ trans('dashboard.statistics_activities') }}</span>
                </li>
                <li class="tc dib mr5">
                  <span class="db f3 fw5 orange">{{ $number_of_gifts }}</span>
                  <span class="stat-description">{{ trans('dashboard.statistics_gifts') }}</span>
                </li>
              </ul>
            </div>
          </div>

          <dashboard-log v-bind:default-active-tab="'{!! auth()->user()->dashboard_active_tab !!}'"></dashboard-log>
        </div>
      </div>
    </section>

  </div>
@endsection