routes/web.php
<?php

use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\URL;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

if (App::environment('production')) {
    URL::forceScheme('https');
}

Route::get('/', 'Auth\LoginController@showLoginOrRegister')->name('login');

Auth::routes();

Route::get('/invitations/accept/{key}', 'SettingsController@acceptInvitation');
Route::post('/invitations/accept/{key}', 'SettingsController@storeAcceptedInvitation')->name('invitations.accept');

Route::middleware(['auth'])->group(function () {
    Route::get('/logout', 'Auth\LoginController@logout');
});

Route::middleware(['auth', '2fa'])->group(function () {
    Route::post('/validate2fa', 'Auth\Validate2faController@index');
});

Route::middleware(['auth', 'auth.confirm', 'u2f', '2fa'])->group(function () {
    Route::name('dashboard.')->group(function () {
        Route::get('/dashboard', 'DashboardController@index')->name('index');
        Route::get('/dashboard/calls', 'DashboardController@calls');
        Route::get('/dashboard/notes', 'DashboardController@notes');
        Route::get('/dashboard/debts', 'DashboardController@debts');
        Route::get('/dashboard/tasks', 'DashboardController@tasks');
        Route::post('/dashboard/setTab', 'DashboardController@setTab');
    });

    Route::get('/compliance', 'ComplianceController@index')->name('compliance');
    Route::post('/compliance/sign', 'ComplianceController@store');
    Route::get('/changelog', 'ChangelogController@index')->name('changelog.index');

    Route::name('people.')->group(function () {
        Route::get('/people', 'ContactsController@index')->name('index');
        Route::get('/people/add', 'ContactsController@create')->name('create');
        Route::get('/people/notfound', 'ContactsController@missing')->name('missing');
        Route::post('/people', 'ContactsController@store')->name('store');

        // Dashboard
        Route::get('/people/{contact}', 'ContactsController@show')->name('show');
        Route::get('/people/{contact}/edit', 'ContactsController@edit')->name('edit');
        Route::post('/people/{contact}/update', 'ContactsController@update')->name('update');
        Route::delete('/people/{contact}', 'ContactsController@delete')->name('delete');

        // Life events
        Route::name('lifeevent.')->group(function () {
            Route::get('/people/{contact}/lifeevents', 'Contacts\\LifeEventsController@index')->name('index');
            Route::get('/lifeevents/categories', 'Contacts\\LifeEventsController@categories')->name('categories');
            Route::get('/lifeevents/categories/{lifeEventCategory}/types', 'Contacts\\LifeEventsController@types')->name('types');
            Route::post('/people/{contact}/lifeevents', 'Contacts\\LifeEventsController@store')->name('store');
            Route::delete('/lifeevents/{lifeevent}', 'Contacts\\LifeEventsController@destroy')->name('destroy');
        });

        // Contact information
        Route::get('/people/{contact}/contactfield', 'Contacts\\ContactFieldsController@getContactFields');
        Route::post('/people/{contact}/contactfield', 'Contacts\\ContactFieldsController@storeContactField');
        Route::put('/people/{contact}/contactfield/{contact_field}', 'Contacts\\ContactFieldsController@editContactField');
        Route::delete('/people/{contact}/contactfield/{contact_field}', 'Contacts\\ContactFieldsController@destroyContactField');
        Route::get('/people/{contact}/contactfieldtypes', 'Contacts\\ContactFieldsController@getContactFieldTypes');

        // Export as vCard
        Route::get('/people/{contact}/vcard', 'ContactsController@vcard')->name('vcard');

        // Addresses
        Route::get('/countries', 'Contacts\\AddressesController@getCountries');
        Route::get('/people/{contact}/addresses', 'Contacts\\AddressesController@get');
        Route::post('/people/{contact}/addresses', 'Contacts\\AddressesController@store');
        Route::put('/people/{contact}/addresses/{address}', 'Contacts\\AddressesController@edit');
        Route::delete('/people/{contact}/addresses/{address}', 'Contacts\\AddressesController@destroy');

        // Work information
        Route::name('work.')->group(function () {
            Route::get('/people/{contact}/work/edit', 'ContactsController@editWork')->name('edit');
            Route::post('/people/{contact}/work/update', 'ContactsController@updateWork')->name('update');
        });

        // Introductions
        Route::name('introductions.')->group(function () {
            Route::get('/people/{contact}/introductions/edit', 'Contacts\\IntroductionsController@edit')->name('edit');
            Route::post('/people/{contact}/introductions/update', 'Contacts\\IntroductionsController@update')->name('update');
        });

        // Tags
        Route::name('tags.')->group(function () {
            Route::post('/people/{contact}/tags/update', 'Contacts\\TagsController@update')->name('update');
        });

        // Notes
        Route::name('notes.')->group(function () {
            Route::get('/people/{contact}/notes', 'Contacts\\NotesController@get');
            Route::post('/people/{contact}/notes', 'Contacts\\NotesController@store')->name('store');
            Route::put('/people/{contact}/notes/{note}', 'Contacts\\NotesController@update');
            Route::delete('/people/{contact}/notes/{note}', 'Contacts\\NotesController@destroy');
            Route::post('/people/{contact}/notes/{note}/toggle', 'Contacts\\NotesController@toggle');
        });

        // Food preferencies
        Route::name('food.')->group(function () {
            Route::get('/people/{contact}/food', 'ContactsController@editFoodPreferencies')->name('index');
            Route::post('/people/{contact}/food/save', 'ContactsController@updateFoodPreferencies')->name('update');
        });

        // Relationships
        Route::name('relationships.')->group(function () {
            Route::get('/people/{contact}/relationships/new', 'Contacts\\RelationshipsController@new')->name('create');
            Route::post('/people/{contact}/relationships/store', 'Contacts\\RelationshipsController@store')->name('store');
            Route::get('/people/{contact}/relationships/{otherContact}/edit', 'Contacts\\RelationshipsController@edit')->name('edit');
            Route::post('/people/{contact}/relationships/{otherContact}', 'Contacts\\RelationshipsController@update')->name('update');
            Route::delete('/people/{contact}/relationships/{otherContact}', 'Contacts\\RelationshipsController@destroy')->name('delete');
        });

        // Pets
        Route::name('pets.')->group(function () {
            Route::get('/people/{contact}/pets', 'Contacts\\PetsController@get')->name('index');
            Route::post('/people/{contact}/pet', 'Contacts\\PetsController@store')->name('store');
            Route::put('/people/{contact}/pet/{pet}', 'Contacts\\PetsController@update')->name('update');
            Route::delete('/people/{contact}/pet/{pet}', 'Contacts\\PetsController@trash')->name('delete');
            Route::get('/petcategories', 'Contacts\\PetsController@getPetCategories');
        });

        // Reminders
        Route::name('reminders.')->group(function () {
            Route::get('/people/{contact}/reminders/add', 'Contacts\\RemindersController@create')->name('add');
            Route::post('/people/{contact}/reminders/store', 'Contacts\\RemindersController@store')->name('store');
            Route::get('/people/{contact}/reminders/{reminder}/edit', 'Contacts\\RemindersController@edit')->name('edit');
            Route::put('/people/{contact}/reminders/{reminder}', 'Contacts\\RemindersController@update')->name('update');
            Route::delete('/people/{contact}/reminders/{reminder}', 'Contacts\\RemindersController@destroy')->name('delete');
        });

        // Tasks
        Route::name('tasks.')->group(function () {
            Route::get('/people/{contact}/tasks', 'Contacts\\TasksController@get')->name('index');
            Route::post('/people/{contact}/tasks', 'Contacts\\TasksController@store')->name('store');
            Route::post('/people/{contact}/tasks/{task}/toggle', 'Contacts\\TasksController@toggle');
            Route::put('/people/{contact}/tasks/{task}', 'Contacts\\TasksController@update')->name('update');
            Route::delete('/people/{contact}/tasks/{task}', 'Contacts\\TasksController@destroy')->name('delete');
        });

        // Gifts
        Route::name('gifts.')->group(function () {
            Route::get('/people/{contact}/gifts', 'Contacts\\GiftsController@get')->name('index');
            Route::post('/people/{contact}/gifts/{gift}/toggle', 'Contacts\\GiftsController@toggle');
            Route::get('/people/{contact}/gifts/add', 'Contacts\\GiftsController@create')->name('add');
            Route::get('/people/{contact}/gifts/{gift}/edit', 'Contacts\\GiftsController@edit')->name('edit');
            Route::post('/people/{contact}/gifts/store', 'Contacts\\GiftsController@store')->name('store');
            Route::post('/people/{contact}/gifts/{gift}/update', 'Contacts\\GiftsController@update')->name('update');
            Route::delete('/people/{contact}/gifts/{gift}', 'Contacts\\GiftsController@destroy')->name('delete');
        });

        // Debt
        Route::name('debt.')->group(function () {
            Route::get('/people/{contact}/debt/add', 'Contacts\\DebtController@create')->name('add');

app/Models/Contact/Debt.php
<?php

namespace App\Models\Contact;

use App\Models\Account\Account;
use Illuminate\Database\Eloquent\Builder;
use App\Models\ModelBindingHasherWithContact as Model;

/**
 * @property Account $account
 * @property Contact $contact
 * @method static Builder due()s
 * @method static Builder owed()
 * @method static Builder inProgress()
 */
class Debt extends Model
{
    /**
     * The attributes that aren't mass assignable.
     *
     * @var array
     */
    protected $guarded = ['id'];

    /**
     * Get the account record associated with the debt.
     */
    public function account()
    {
        return $this->belongsTo(Account::class);
    }

    /**
     * Get the contact record associated with the debt.
     */
    public function contact()
    {
        return $this->belongsTo(Contact::class);
    }

    /**
     * Limit results to unpaid/unreceived debt.
     *
     * @param Builder $query
     * @return Builder
     */
    public function scopeInProgress(Builder $query)
    {
        return $query->where('status', 'inprogress');
    }

    /**
     * Limit results to due debt.
     *
     * @param Builder $query
     * @return Builder
     */
    public function scopeDue(Builder $query)
    {
        return $query->where('in_debt', 'yes');
    }

    /**
     * Limit results to owed debt.
     *
     * @param Builder $query
     * @return Builder
     */
    public function scopeOwed(Builder $query)
    {
        return $query->where('in_debt', 'no');
    }
}

app/Http/Controllers/Contacts/DebtController.php
<?php

namespace App\Http\Controllers\Contacts;

use App\Models\Contact\Debt;
use App\Models\Contact\Contact;
use App\Http\Controllers\Controller;
use App\Http\Requests\People\DebtRequest;

class DebtController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @param Contact $contact
     * @return \Illuminate\Http\Response
     */
    public function index(Contact $contact)
    {
        return view('people.debt.index')
            ->withContact($contact);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @param Contact $contact
     * @return \Illuminate\Http\Response
     */
    public function create(Contact $contact)
    {
        return view('people.debt.add')
            ->withContact($contact)
            ->withDebt(new Debt);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param DebtRequest $request
     * @param Contact $contact
     * @return \Illuminate\Http\Response
     */
    public function store(DebtRequest $request, Contact $contact)
    {
        $contact->debts()->create(
            $request->only([
                'in_debt',
                'amount',
                'reason',
            ])
            + [
                'account_id' => $contact->account_id,
                'status' => 'inprogress',
            ]
        );

        return redirect()->route('people.show', $contact)
            ->with('success', trans('people.debt_add_success'));
    }

    /**
     * Display the specified resource.
     *
     * @param Contact $contact
     * @param Debt $debt
     * @return \Illuminate\Http\Response
     */
    public function show(Contact $contact, Debt $debt)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Contact $contact
     * @param Debt $debt
     * @return \Illuminate\Http\Response
     */
    public function edit(Contact $contact, Debt $debt)
    {
        return view('people.debt.edit')
            ->withContact($contact)
            ->withDebt($debt);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param DebtRequest $request
     * @param Contact $contact
     * @param Debt $debt
     * @return \Illuminate\Http\Response
     */
    public function update(DebtRequest $request, Contact $contact, Debt $debt)
    {
        $debt->update(
            $request->only([
                'in_debt',
                'amount',
                'reason',
            ])
            + [
                'account_id' => $contact->account_id,
                'status' => 'inprogress',
            ]
        );

        return redirect()->route('people.show', $contact)
            ->with('success', trans('people.debt_edit_success'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Contact $contact
     * @param Debt $debt
     * @return \Illuminate\Http\Response
     */
    public function destroy(Contact $contact, Debt $debt)
    {
        $debt->delete();

        return redirect()->route('people.show', $contact)
            ->with('success', trans('people.debt_delete_success'));
    }
}

resources/views/people/debt/add.blade.php
@extends('layouts.skeleton')

@section('content')
  <div class="people-show debt">

    {{-- Breadcrumb --}}
    <div class="breadcrumb">
      <div class="{{ Auth::user()->getFluidLayout() }}">
        <div class="row">
          <div class="col-xs-12">
            <ul class="horizontal">
              <li>
                <a href="{{ route('dashboard.index') }}">{{ trans('app.breadcrumb_dashboard') }}</a>
              </li>
              <li>
                <a href="{{ route('people.index') }}">{{ trans('app.breadcrumb_list_contacts') }}</a>
              </li>
              <li>
                {{ $contact->name }}
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>

    <!-- Page header -->
    @include('people._header')

    <!-- Page content -->
    <div class="main-content central-form">
      <div class="{{ Auth::user()->getFluidLayout() }}">
        <div class="row">
          <div class="col-xs-12 col-sm-6 col-sm-offset-3 col-sm-offset-3-right">
            @include('people.debt.form', [
              'method' => 'POST',
              'action' => route('people.debt.store', $contact),
              'update_or_add' =>'add'
            ])
          </div>
        </div>
      </div>
    </div>

  </div>
@endsection

resources/views/people/debt/edit.blade.php
@extends('layouts.skeleton')

@section('content')
  <div class="people-show debt">

    {{-- Breadcrumb --}}
    <div class="breadcrumb">
      <div class="{{ Auth::user()->getFluidLayout() }}">
        <div class="row">
          <div class="col-xs-12">
            <ul class="horizontal">
              <li>
                <a href="{{ route('dashboard.index') }}">{{ trans('app.breadcrumb_dashboard') }}</a>
              </li>
              <li>
                <a href="{{ route('people.index') }}">{{ trans('app.breadcrumb_list_contacts') }}</a>
              </li>
              <li>
                {{ $contact->name }}
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>

    <!-- Page header -->
    @include('people._header')

    <!-- Page content -->
    <div class="main-content central-form">
      <div class="{{ Auth::user()->getFluidLayout() }}">
        <div class="row">
          <div class="col-xs-12 col-sm-6 col-sm-offset-3 col-sm-offset-3-right">
            @include('people.debt.form', [
              'method' => 'PUT',
              'action' => route('people.debt.update', [$contact, $debt]),
              'update_or_add' =>'edit'
            ])
          </div>
        </div>
      </div>
    </div>

  </div>
@endsection

resources/views/people/debt/form.blade.php
<form method="POST" action="{{ $action }}">
    {{ method_field($method) }}
    {{ csrf_field() }}

    @include('partials.errors')

    <h2>{{ trans('people.debt_add_title') }}</h2>

    {{-- Gender --}}
    <fieldset class="form-group">
        <label class="form-check-inline" for="youowe">
            <input type="radio" class="form-check-input" name="in_debt" id="youowe" value="yes" @if(old('in_debt') !== 'no' || $debt->in_debt !== 'no') checked @endif>
            {{ trans('people.debt_add_you_owe', ['name' => $contact->first_name]) }}
        </label>

        <label class="form-check-inline" for="theyowe">
            <input type="radio" class="form-check-input" name="in_debt" id="theyowe" value="no">
            {{ trans('people.debt_add_they_owe', ['name' => $contact->first_name]) }}
        </label>
    </fieldset>

    {{-- Amount --}}
    <div class="form-group">
        <label for="amount">{{ trans('people.debt_add_amount') }} ({{ Auth::user()->currency->symbol }})</label>
        <input type="number" step=".01" class="form-control" name="amount" id="amount" maxlength="254" value="{{ old('amount') ?? $debt->amount }}" autofocus required>
    </div>

    {{-- Reason --}}
    <div class="form-group">
        <label for="reason">{{ trans('people.debt_add_reason') }}</label>
        <textarea class="form-control" name="reason" id="reason" maxlength="2500">{{ old('reason') ?? $debt->reason }}</textarea>
    </div>

    <div class="form-group actions">
        <button type="submit" cy-name="save-debt-button" class="btn btn-primary">
            @if($update_or_add == 'add')
            {{ trans('people.debt_add_add_cta') }}
            @elseif ($update_or_add == 'edit')
            {{ trans('people.debt_edit_update_cta') }}
            @endif
        </button>
        <a href="{{ route('people.show', $contact) }}" class="btn btn-secondary">{{ trans('app.cancel') }}</a>
    </div> <!-- .form-group -->
</form>

resources/views/people/debt/index.blade.php
<div class="col-xs-12 section-title">
  <img src="/img/people/debt/bill.svg" class="icon-section icon-money">
  <h3>
    {{ trans('people.debt_title') }}

    <span class="{{ htmldir() == 'ltr' ? 'fr' : 'fl' }}">
      <a href="{{ route('people.debt.add', $contact) }}" class="btn">{{ trans('people.debt_add_cta') }}</a>
    </span>
  </h3>
</div>

@if (!$contact->hasDebt())

  <div class="col-xs-12" cy-name="debt-blank-state">
    <div class="section-blank">
      <h3>{{ trans('people.debts_blank_title', ['name' => $contact->first_name]) }}</h3>
      <a href="{{ route('people.debt.add', $contact) }}" cy-name="add-debt-button">{{ trans('people.debt_add_cta') }}</a>
    </div>
  </div>

@else

  <div class="col-xs-12 debts-list">

    <ul class="table">
      @foreach($contact->debts as $debt)
      <li class="table-row" cy-name="debt-item-{{ $debt->id }}">
        <div class="table-cell date">
          {{ \App\Helpers\DateHelper::getShortDate($debt->created_at) }}
        </div>
        <div class="table-cell debt-nature">
          @if ($debt->in_debt == 'yes')
            {{ trans('people.debt_you_owe', [
                'amount' => App\Helpers\MoneyHelper::format($debt->amount)
            ]) }}
          @else
            {{ trans('people.debt_they_owe', [
                'name' => $contact->first_name,
                'amount' => App\Helpers\MoneyHelper::format($debt->amount)
            ]) }}
          @endif
        </div>
        <div class="table-cell reason">
          @if (! is_null($debt->reason))
            {{ $debt->reason }}
          @endif
        </div>
        <div class="table-cell list-actions">
          <a href="{{ route('people.debt.edit', [$contact, $debt]) }}" cy-name="edit-debt-button-{{ $debt->id }}">
            <i class="fa fa-pencil" aria-hidden="true"></i>
          </a>
          <a href="#" cy-name="delete-debt-button-{{ $debt->id }}" onclick="if (confirm('{{ trans('people.debt_delete_confirmation') }}')) { $(this).closest('.table-row').find('.entry-delete-form').submit(); } return false;">
            <i class="fa fa-trash-o" aria-hidden="true"></i>
          </a>
        </div>

        <form method="POST" action="{{ route('people.debt.delete', [$contact, $debt]) }}" class="entry-delete-form hidden">
          {{ method_field('DELETE') }}
          {{ csrf_field() }}
        </form>
      </li>
      @endforeach
      <li class="table-row">
        <div class="table-cell"></div>
        <div class="table-cell">
          <strong>
            @if ($contact->isOwedMoney())
              {{ trans('people.debt_they_owe', [
                  'name' => $contact->first_name,
                  'amount' => App\Helpers\MoneyHelper::format($contact->totalOutstandingDebtAmount())
              ]) }}
            @else
              {{ trans('people.debt_you_owe', [
                  'amount' => App\Helpers\MoneyHelper::format(-$contact->totalOutstandingDebtAmount())
              ]) }}
            @endif
          </strong>
        </div>
        <div class="table-cell"></div>
        <div class="table-cell"></div>
      </li>
    </ul>

  </div>

@endif