routes/web.php
            Route::delete('/people/{contact}/debt/{debt}', 'Contacts\\DebtController@destroy')->name('delete');
        });

        // Phone calls
        Route::name('call.')->group(function () {
            Route::post('/people/{contact}/call/store', 'Contacts\\CallsController@store')->name('store');
            Route::delete('/people/{contact}/call/{call}', 'Contacts\\CallsController@destroy')->name('delete');
        });

        // Conversations
        Route::name('conversation.')->group(function () {
            Route::get('/people/{contact}/conversations', 'Contacts\\ConversationsController@index')->name('index');
            Route::get('/people/{contact}/conversation/new', 'Contacts\\ConversationsController@new')->name('new');
            Route::post('/people/{contact}/conversation/store', 'Contacts\\ConversationsController@store')->name('store');
            Route::get('/people/{contact}/conversation/{conversation}/edit', 'Contacts\\ConversationsController@edit')->name('edit');
            Route::post('/people/{contact}/conversation/{conversation}', 'Contacts\\ConversationsController@update')->name('update');
            Route::delete('/people/{contact}/conversation/{conversation}', 'Contacts\\ConversationsController@destroy')->name('destroy');
        });

        // Search
        Route::post('/people/search', 'ContactsController@search')->name('search');

        // Stay in touch information
        Route::post('/people/{contact}/stayintouch', 'ContactsController@stayInTouch');

        // Set favorite
        Route::post('/people/{contact}/favorite', 'ContactsController@favorite');

        // Activities
        Route::get('/people/{contact}/activities', 'Contacts\\ActivitiesController@index')->name('activities.index');
        Route::get('/people/{contact}/activities/{year}', 'Contacts\\ActivitiesController@year')->name('activities.year');
    });

    // Activities
    Route::name('activities.')->group(function () {
        Route::get('/activities/add/{contact}', 'ActivitiesController@create')->name('add');
        Route::post('/activities/store/{contact}', 'ActivitiesController@store')->name('store');
        Route::get('/activities/{activity}/edit/{contact}', 'ActivitiesController@edit')->name('edit');
        Route::put('/activities/{activity}/{contact}', 'ActivitiesController@update')->name('update');
        Route::delete('/activities/{activity}/{contact}', 'ActivitiesController@destroy')->name('delete');
    });

    Route::name('journal.')->group(function () {
        Route::get('/journal', 'JournalController@index')->name('index');
        Route::get('/journal/entries', 'JournalController@list')->name('list');
        Route::get('/journal/entries/{journalEntry}', 'JournalController@get');
        Route::get('/journal/hasRated', 'JournalController@hasRated');
        Route::post('/journal/day', 'JournalController@storeDay');
        Route::delete('/journal/day/{day}', 'JournalController@trashDay');

        Route::get('/journal/add', 'JournalController@create')->name('create');
        Route::post('/journal/create', 'JournalController@save')->name('save');
        Route::delete('/journal/{entryId}', 'JournalController@deleteEntry');
    });

    Route::name('settings.')->group(function () {
        Route::get('/settings', 'SettingsController@index')->name('index');
        Route::post('/settings/delete', 'SettingsController@delete')->name('delete');
        Route::post('/settings/reset', 'SettingsController@reset')->name('reset');
        Route::post('/settings/save', 'SettingsController@save')->name('save');

        Route::name('personalization.')->group(function () {
            Route::get('/settings/personalization', 'Settings\\PersonalizationController@index')->name('index');
            Route::get('/settings/personalization/contactfieldtypes', 'Settings\\PersonalizationController@getContactFieldTypes');
            Route::post('/settings/personalization/contactfieldtypes', 'Settings\\PersonalizationController@storeContactFieldType');
            Route::put('/settings/personalization/contactfieldtypes/{contactfieldtype_id}', 'Settings\\PersonalizationController@editContactFieldType');
            Route::delete('/settings/personalization/contactfieldtypes/{contactfieldtype_id}', 'Settings\\PersonalizationController@destroyContactFieldType');

            Route::get('/settings/personalization/genders', 'Settings\\GendersController@getGenderTypes');
            Route::post('/settings/personalization/genders', 'Settings\\GendersController@storeGender');
            Route::put('/settings/personalization/genders/{gender}', 'Settings\\GendersController@updateGender');
            Route::delete('/settings/personalization/genders/{gender}/replaceby/{gender_id}', 'Settings\\GendersController@destroyAndReplaceGender');
            Route::delete('/settings/personalization/genders/{gender}', 'Settings\\GendersController@destroyGender');

            Route::get('/settings/personalization/reminderrules', 'Settings\\ReminderRulesController@get');
            Route::post('/settings/personalization/reminderrules/{reminderRule}', 'Settings\\ReminderRulesController@toggle');

            Route::get('/settings/personalization/modules', 'Settings\\ModulesController@get');
            Route::post('/settings/personalization/modules/{module}', 'Settings\\ModulesController@toggle');

            Route::get('/settings/personalization/activitytypecategories', 'Settings\\ActivityTypeCategoriesController@index');
            Route::post('/settings/personalization/activitytypecategories', 'Settings\\ActivityTypeCategoriesController@create');
            Route::put('/settings/personalization/activitytypecategories', 'Settings\\ActivityTypeCategoriesController@update');
            Route::delete('/settings/personalization/activitytypecategories/{activityTypeCategory}', 'Settings\\ActivityTypeCategoriesController@destroy');

            Route::post('/settings/personalization/activitytypes', 'Settings\\ActivityTypesController@create');
            Route::put('/settings/personalization/activitytypes', 'Settings\\ActivityTypesController@update');
            Route::delete('/settings/personalization/activitytypes/{activityType}', 'Settings\\ActivityTypesController@destroy');
        });

        Route::get('/settings/export', 'SettingsController@export')->name('export');
        Route::get('/settings/exportToSql', 'SettingsController@exportToSQL')->name('sql');
        Route::get('/settings/import', 'SettingsController@import')->name('import');
        Route::get('/settings/import/report/{importjobid}', 'SettingsController@report')->name('report');
        Route::get('/settings/import/upload', 'SettingsController@upload')->name('upload');
        Route::post('/settings/import/storeImport', 'SettingsController@storeImport')->name('storeImport');

        Route::name('users.')->group(function () {
            Route::get('/settings/users', 'SettingsController@users')->name('index');
            Route::get('/settings/users/add', 'SettingsController@addUser')->name('add');
            Route::delete('/settings/users/{user}', 'SettingsController@deleteAdditionalUser')->name('delete');
            Route::post('/settings/users/save', 'SettingsController@inviteUser')->name('save');
            Route::delete('/settings/users/invitations/{invitation}', 'SettingsController@destroyInvitation')->name('invitation.delete');
        });

        Route::name('subscriptions.')->group(function () {
            Route::get('/settings/subscriptions', 'Settings\\SubscriptionsController@index')->name('index');
            Route::get('/settings/subscriptions/upgrade', 'Settings\\SubscriptionsController@upgrade')->name('upgrade');
            Route::get('/settings/subscriptions/upgrade/success', 'Settings\\SubscriptionsController@upgradeSuccess')->name('upgrade.success');
            Route::post('/settings/subscriptions/processPayment', 'Settings\\SubscriptionsController@processPayment')->name('payment');
            Route::get('/settings/subscriptions/invoice/{invoice}', 'Settings\\SubscriptionsController@downloadInvoice')->name('invoice');
            Route::get('/settings/subscriptions/downgrade', 'Settings\\SubscriptionsController@downgrade')->name('downgrade');
            Route::post('/settings/subscriptions/downgrade', 'Settings\\SubscriptionsController@processDowngrade');
            Route::get('/settings/subscriptions/downgrade/success', 'Settings\\SubscriptionsController@downgradeSuccess')->name('downgrade.success');
        });

        Route::name('tags.')->group(function () {
            Route::get('/settings/tags', 'SettingsController@tags')->name('index');
            Route::get('/settings/tags/add', 'SettingsController@addUser')->name('add');
            Route::delete('/settings/tags/{tag}', 'SettingsController@deleteTag')->name('delete');
        });

        Route::get('/settings/api', 'SettingsController@api')->name('api');

        Route::post('/settings/updateDefaultProfileView', 'SettingsController@updateDefaultProfileView');

        // Security
        Route::name('security.')->group(function () {
            Route::get('/settings/security', 'SettingsController@security')->name('index');
            Route::post('/settings/security/passwordChange', 'Auth\\PasswordChangeController@passwordChange')->name('passwordChange');
            Route::get('/settings/security/2fa-enable', 'Settings\\MultiFAController@enableTwoFactor')->name('2fa-enable');
            Route::post('/settings/security/2fa-enable', 'Settings\\MultiFAController@validateTwoFactor');
            Route::get('/settings/security/2fa-disable', 'Settings\\MultiFAController@disableTwoFactor')->name('2fa-disable');
            Route::post('/settings/security/2fa-disable', 'Settings\\MultiFAController@deactivateTwoFactor');
            Route::get('/settings/security/u2f-register', 'Settings\\MultiFAController@u2fRegister')->name('u2f-register');
        });
    });

app/Models/Contact/Call.php
<?php

namespace App\Models\Contact;

use Parsedown;
use App\Models\Account\Account;
use App\Models\ModelBindingWithContact as Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Call extends Model
{
    /**
     * The attributes that aren't mass assignable.
     *
     * @var array
     */
    protected $guarded = ['id'];

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['called_at'];

    /**
     * Get the account record associated with the call.
     *
     * @return BelongsTo
     */
    public function account()
    {
        return $this->belongsTo(Account::class);
    }

    /**
     * Get the contact record associated with the call.
     *
     * @return BelongsTo
     */
    public function contact()
    {
        return $this->belongsTo(Contact::class);
    }

    /**
     * Return the markdown parsed body.
     *
     * @return string
     */
    public function getParsedContentAttribute()
    {
        if (is_null($this->content)) {
            return;
        }

        return (new Parsedown())->text($this->content);
    }
}

resources/views/people/modal/activity_view.blade.php
<!-- Modal -->
<div class="modal log-call fade" id="activity{{$activity->id}}Modal" tabindex="-1">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        {{ $activity->getSummary() }}
        <button type="button" class="close" data-dismiss="modal">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

              <label for="summary">{{ trans('people.activities_who_was_involved') }}</label>
                  <ul class="contacts">
                      <ul class="contacts-list">
                          @foreach ($activity->contacts as $contact)
                              <li class="pretty-tag"><a href="{{ route('people.show', $contact) }}">{{ $contact->first_name }} {{ $contact->last_name }}</a></li>
                          @endforeach
                      </ul>
                  </ul>
                  <br>

                  <label for="date_it_happened">{{ trans('people.activities_add_date_occured') }}</label>
                  <p>{{ \App\Helpers\DateHelper::getShortDate($activity->date_it_happened) }}</p>
                  <br>

                  <label for="activity_type_id">{{ trans('people.activities_activity') }}</label>
                  @if (isset($activity->type))
                     <p>{{ $activity->type->name }}</p>
                  @else
                     <p>{{ trans('app.unknown')}}</p>
                  @endif
                  <br>

                  <label for="description">{{ trans('people.activities_add_optional_comment') }}</label>
                  <div class="markdown">
                  {!! $activity->parsed_content !!}
                  </div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">{{ trans('app.close') }}</button>
      </div>
    </div>
  </div>
</div>

resources/views/people/modal/log_call.blade.php
<!-- Modal -->
<div class="modal log-call fade" id="logCallModal" tabindex="-1">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">{{ trans('people.modal_call_title') }}</h5>
        <button type="button" class="close" data-dismiss="modal">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form method="POST" action="{{ route('people.call.store', $contact) }}">
          {{ csrf_field() }}

          <div class="form-group">
            <label for="content" class="form-control-label b">{{ trans('people.modal_call_comment') }}</label>
            <textarea class="form-control mb3" name="content" id="content" maxlength="2500" autofocus>
            </textarea>

            <p class="f6">{{ trans('app.markdown_description')}} <a href="https://guides.github.com/features/mastering-markdown/" target="_blank">{{ trans('app.markdown_link') }}</a></p>

            <p class="date-it-happened">
              {{ trans('people.modal_call_date') }} <a href="#" class="change-date-happened">{{ trans('people.modal_call_change') }}</a>
            </p>

            <p class="exact-date">
              {{ trans('people.modal_call_exact_date') }}
              <input type="date" name="called_at" class="form-control"
                           value="{{ now(\App\Helpers\DateHelper::getTimezone())->toDateString() }}"
                           min="{{ now(\App\Helpers\DateHelper::getTimezone())->subYears(120)->toDateString() }}"
                           max="{{ now(\App\Helpers\DateHelper::getTimezone())->toDateString() }}">
            </p>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">{{ trans('app.cancel') }}</button>
        <button type="button" cy-name="save-call-button" class="btn btn-primary modal-cta">{{ trans('app.save') }}</button>
      </div>
    </div>
  </div>
</div>