routes/web.php
            Route::post('/people/{contact}/gifts/{gift}/toggle', 'Contacts\\GiftsController@toggle');
            Route::get('/people/{contact}/gifts/add', 'Contacts\\GiftsController@create')->name('add');
            Route::get('/people/{contact}/gifts/{gift}/edit', 'Contacts\\GiftsController@edit')->name('edit');
            Route::post('/people/{contact}/gifts/store', 'Contacts\\GiftsController@store')->name('store');
            Route::post('/people/{contact}/gifts/{gift}/update', 'Contacts\\GiftsController@update')->name('update');
            Route::delete('/people/{contact}/gifts/{gift}', 'Contacts\\GiftsController@destroy')->name('delete');
        });

        // Debt
        Route::name('debt.')->group(function () {
            Route::get('/people/{contact}/debt/add', 'Contacts\\DebtController@create')->name('add');
            Route::post('/people/{contact}/debt/store', 'Contacts\\DebtController@store')->name('store');
            Route::get('/people/{contact}/debt/{debt}/edit', 'Contacts\\DebtController@edit')->name('edit');
            Route::put('/people/{contact}/debt/{debt}', 'Contacts\\DebtController@update')->name('update');
            Route::delete('/people/{contact}/debt/{debt}', 'Contacts\\DebtController@destroy')->name('delete');
        });

        // Phone calls
        Route::name('call.')->group(function () {
            Route::post('/people/{contact}/call/store', 'Contacts\\CallsController@store')->name('store');
            Route::delete('/people/{contact}/call/{call}', 'Contacts\\CallsController@destroy')->name('delete');
        });

        // Conversations
        Route::name('conversation.')->group(function () {
            Route::get('/people/{contact}/conversations', 'Contacts\\ConversationsController@index')->name('index');
            Route::get('/people/{contact}/conversation/new', 'Contacts\\ConversationsController@new')->name('new');
            Route::post('/people/{contact}/conversation/store', 'Contacts\\ConversationsController@store')->name('store');
            Route::get('/people/{contact}/conversation/{conversation}/edit', 'Contacts\\ConversationsController@edit')->name('edit');
            Route::post('/people/{contact}/conversation/{conversation}', 'Contacts\\ConversationsController@update')->name('update');
            Route::delete('/people/{contact}/conversation/{conversation}', 'Contacts\\ConversationsController@destroy')->name('destroy');
        });

        // Search
        Route::post('/people/search', 'ContactsController@search')->name('search');

        // Stay in touch information
        Route::post('/people/{contact}/stayintouch', 'ContactsController@stayInTouch');

        // Set favorite
        Route::post('/people/{contact}/favorite', 'ContactsController@favorite');

        // Activities
        Route::get('/people/{contact}/activities', 'Contacts\\ActivitiesController@index')->name('activities.index');
        Route::get('/people/{contact}/activities/{year}', 'Contacts\\ActivitiesController@year')->name('activities.year');
    });

    // Activities
    Route::name('activities.')->group(function () {
        Route::get('/activities/add/{contact}', 'ActivitiesController@create')->name('add');
        Route::post('/activities/store/{contact}', 'ActivitiesController@store')->name('store');
        Route::get('/activities/{activity}/edit/{contact}', 'ActivitiesController@edit')->name('edit');
        Route::put('/activities/{activity}/{contact}', 'ActivitiesController@update')->name('update');
        Route::delete('/activities/{activity}/{contact}', 'ActivitiesController@destroy')->name('delete');
    });

    Route::name('journal.')->group(function () {
        Route::get('/journal', 'JournalController@index')->name('index');
        Route::get('/journal/entries', 'JournalController@list')->name('list');
        Route::get('/journal/entries/{journalEntry}', 'JournalController@get');
        Route::get('/journal/hasRated', 'JournalController@hasRated');
        Route::post('/journal/day', 'JournalController@storeDay');
        Route::delete('/journal/day/{day}', 'JournalController@trashDay');

        Route::get('/journal/add', 'JournalController@create')->name('create');
        Route::post('/journal/create', 'JournalController@save')->name('save');
        Route::delete('/journal/{entryId}', 'JournalController@deleteEntry');
    });

    Route::name('settings.')->group(function () {
        Route::get('/settings', 'SettingsController@index')->name('index');
        Route::post('/settings/delete', 'SettingsController@delete')->name('delete');
        Route::post('/settings/reset', 'SettingsController@reset')->name('reset');
        Route::post('/settings/save', 'SettingsController@save')->name('save');

        Route::name('personalization.')->group(function () {
            Route::get('/settings/personalization', 'Settings\\PersonalizationController@index')->name('index');
            Route::get('/settings/personalization/contactfieldtypes', 'Settings\\PersonalizationController@getContactFieldTypes');
            Route::post('/settings/personalization/contactfieldtypes', 'Settings\\PersonalizationController@storeContactFieldType');
            Route::put('/settings/personalization/contactfieldtypes/{contactfieldtype_id}', 'Settings\\PersonalizationController@editContactFieldType');
            Route::delete('/settings/personalization/contactfieldtypes/{contactfieldtype_id}', 'Settings\\PersonalizationController@destroyContactFieldType');

            Route::get('/settings/personalization/genders', 'Settings\\GendersController@getGenderTypes');
            Route::post('/settings/personalization/genders', 'Settings\\GendersController@storeGender');
            Route::put('/settings/personalization/genders/{gender}', 'Settings\\GendersController@updateGender');
            Route::delete('/settings/personalization/genders/{gender}/replaceby/{gender_id}', 'Settings\\GendersController@destroyAndReplaceGender');
            Route::delete('/settings/personalization/genders/{gender}', 'Settings\\GendersController@destroyGender');

            Route::get('/settings/personalization/reminderrules', 'Settings\\ReminderRulesController@get');
            Route::post('/settings/personalization/reminderrules/{reminderRule}', 'Settings\\ReminderRulesController@toggle');

            Route::get('/settings/personalization/modules', 'Settings\\ModulesController@get');
            Route::post('/settings/personalization/modules/{module}', 'Settings\\ModulesController@toggle');

            Route::get('/settings/personalization/activitytypecategories', 'Settings\\ActivityTypeCategoriesController@index');
            Route::post('/settings/personalization/activitytypecategories', 'Settings\\ActivityTypeCategoriesController@create');
            Route::put('/settings/personalization/activitytypecategories', 'Settings\\ActivityTypeCategoriesController@update');
            Route::delete('/settings/personalization/activitytypecategories/{activityTypeCategory}', 'Settings\\ActivityTypeCategoriesController@destroy');

            Route::post('/settings/personalization/activitytypes', 'Settings\\ActivityTypesController@create');
            Route::put('/settings/personalization/activitytypes', 'Settings\\ActivityTypesController@update');
            Route::delete('/settings/personalization/activitytypes/{activityType}', 'Settings\\ActivityTypesController@destroy');
        });

        Route::get('/settings/export', 'SettingsController@export')->name('export');
        Route::get('/settings/exportToSql', 'SettingsController@exportToSQL')->name('sql');
        Route::get('/settings/import', 'SettingsController@import')->name('import');
        Route::get('/settings/import/report/{importjobid}', 'SettingsController@report')->name('report');
        Route::get('/settings/import/upload', 'SettingsController@upload')->name('upload');
        Route::post('/settings/import/storeImport', 'SettingsController@storeImport')->name('storeImport');

        Route::name('users.')->group(function () {
            Route::get('/settings/users', 'SettingsController@users')->name('index');
            Route::get('/settings/users/add', 'SettingsController@addUser')->name('add');
            Route::delete('/settings/users/{user}', 'SettingsController@deleteAdditionalUser')->name('delete');
            Route::post('/settings/users/save', 'SettingsController@inviteUser')->name('save');
            Route::delete('/settings/users/invitations/{invitation}', 'SettingsController@destroyInvitation')->name('invitation.delete');
        });

        Route::name('subscriptions.')->group(function () {
            Route::get('/settings/subscriptions', 'Settings\\SubscriptionsController@index')->name('index');
            Route::get('/settings/subscriptions/upgrade', 'Settings\\SubscriptionsController@upgrade')->name('upgrade');
            Route::get('/settings/subscriptions/upgrade/success', 'Settings\\SubscriptionsController@upgradeSuccess')->name('upgrade.success');
            Route::post('/settings/subscriptions/processPayment', 'Settings\\SubscriptionsController@processPayment')->name('payment');
            Route::get('/settings/subscriptions/invoice/{invoice}', 'Settings\\SubscriptionsController@downloadInvoice')->name('invoice');
            Route::get('/settings/subscriptions/downgrade', 'Settings\\SubscriptionsController@downgrade')->name('downgrade');
            Route::post('/settings/subscriptions/downgrade', 'Settings\\SubscriptionsController@processDowngrade');
            Route::get('/settings/subscriptions/downgrade/success', 'Settings\\SubscriptionsController@downgradeSuccess')->name('downgrade.success');
        });

        Route::name('tags.')->group(function () {
            Route::get('/settings/tags', 'SettingsController@tags')->name('index');
            Route::get('/settings/tags/add', 'SettingsController@addUser')->name('add');

app/Models/Contact/ActivityType.php
<?php

namespace App\Models\Contact;

use App\Models\Account\Account;
use App\Models\ModelBinding as Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class ActivityType extends Model
{
    protected $table = 'activity_types';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'activity_type_category_id',
        'account_id',
    ];

    /**
     * Get the account record associated with the activity type.
     *
     * @return BelongsTo
     */
    public function account()
    {
        return $this->belongsTo(Account::class);
    }

    /**
     * Get the activity type category record associated with the activity types.
     */
    public function category()
    {
        return $this->belongsTo(ActivityTypeCategory::class, 'activity_type_category_id');
    }

    /**
     * Get the activity records associated with the activity type.
     */
    public function activities()
    {
        return $this->hasMany(Activity::class);
    }

    /**
     * Get the activity type's attribute.
     */
    public function getNameAttribute($value)
    {
        if ($this->translation_key && ! $value) {
            return trans('people.activity_type_'.$this->translation_key);
        }

        return $value;
    }

    /**
     * Reset all associated activities with this category type.
     *
     * @return void
     */
    public function resetAssociationWithActivities()
    {
        foreach ($this->activities as $activity) {
            $activity->activity_type_id = null;
            $activity->save();
        }
    }
}

app/Http/Controllers/ActivitiesController.php
<?php

namespace App\Http\Controllers;

use App\Models\Contact\Contact;
use App\Models\Contact\Activity;
use App\Models\Journal\JournalEntry;
use App\Http\Requests\People\ActivitiesRequest;
use Illuminate\Database\Eloquent\ModelNotFoundException;

class ActivitiesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @param Contact $contact
     * @return \Illuminate\Http\Response
     */
    public function index(Contact $contact)
    {
        return view('activities.index')
            ->withContact($contact);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @param Contact $contact
     * @return \Illuminate\Http\Response
     */
    public function create(Contact $contact)
    {
        return view('activities.add')
            ->withContact($contact)
            ->withActivity(new Activity);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param ActivitiesRequest $request
     * @param Contact $contact
     * @return \Illuminate\Http\Response
     */
    public function store(ActivitiesRequest $request, Contact $contact)
    {
        $specifiedContacts = $request->get('contacts');
        $specifiedContactsObj = [];

        try {
            // Test if every attached contact are found before creating the activity
            foreach ($specifiedContacts as $newContactId) {
                $newContact = Contact::where('account_id', $request->user()->account_id)
                    ->findOrFail($newContactId);
                array_push($specifiedContactsObj, $newContact);
            }
        } catch (ModelNotFoundException $e) {
            return redirect()->route('people.show', $contact)
                ->withErrors(trans('people.activities_add_error'));
        }

        $activity = Activity::create(
            $request->only([
                'summary',
                'date_it_happened',
                'activity_type_id',
                'description',
            ])
            + ['account_id' => $request->user()->account_id]
        );

        // New attendees
        foreach ($specifiedContactsObj as $newContact) {
            $newContact->activities()->attach($activity, ['account_id' => $request->user()->account_id]);
            $newContact->calculateActivitiesStatistics();
        }

        // Log a journal entry
        (new JournalEntry)->add($activity);

        return redirect()->route('people.show', $contact)
            ->with('success', trans('people.activities_add_success'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Contact $contact
     * @param Activity $activity
     * @return \Illuminate\Http\Response
     */
    public function edit(Activity $activity, Contact $contact)
    {
        return view('activities.edit')
            ->withContact($contact)
            ->withActivity($activity);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param ActivitiesRequest $request
     * @param Contact $contact
     * @param Activity $activity
     * @return \Illuminate\Http\Response
     */
    public function update(ActivitiesRequest $request, Activity $activity, Contact $contact)
    {
        $user = $request->user();
        $account = $user->account;
        $specifiedContacts = $request->get('contacts');
        $specifiedContactsObj = [];

        try {
            // Test if every attached contact are found before updating the activity
            foreach ($specifiedContacts as $newContactId) {
                $specifiedContactsObj[$newContactId] = Contact::where('account_id', $account->id)
                    ->findOrFail($newContactId);
            }
        } catch (ModelNotFoundException $e) {
            return redirect()->route('people.show', $contact)
                ->withErrors(trans('people.activities_add_error'));
        }

        $activity->update(
            $request->only([
                'summary',
                'date_it_happened',
                'activity_type_id',
                'description',
            ])
            + ['account_id' => $account->id]
        );

        // Find existing attendees
        $existing = $activity->contacts()->get();

        foreach ($existing as $existingContact) {
            // Has an existing attendee been removed?
            if (! array_key_exists($existingContact->id, $specifiedContactsObj)) {
                $existingContact->activities()->detach($activity);
            }

            // Remove this ID from our list of contacts as we don't
            // want to add them to the activity again
            unset($specifiedContactsObj[$existingContact->id]);

            $existingContact->calculateActivitiesStatistics();
        }

        // New attendees
        foreach ($specifiedContactsObj as $newContact) {
            $newContact->activities()->save($activity);
        }

        return redirect()->route('people.show', $contact)
            ->with('success', trans('people.activities_update_success'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Contact $contact
     * @param Activity $activity
     * @return \Illuminate\Http\Response
     */
    public function destroy(Activity $activity, Contact $contact)
    {
        $activity->deleteJournalEntry();

        foreach ($activity->contacts as $contactActivity) {
            $contactActivity->calculateActivitiesStatistics();
        }

        $activity->delete();

        return redirect()->route('people.show', $contact)
            ->with('success', trans('people.activities_delete_success'));
    }
}

resources/views/activities/add.blade.php
@extends('layouts.skeleton')

@section('content')
  <div class="people-show activities">

    {{-- Breadcrumb --}}
    <div class="breadcrumb">
      <div class="{{ Auth::user()->getFluidLayout() }}">
        <div class="row">
          <div class="col-xs-12">
            <ul class="horizontal">
              <li>
                <a href="{{ route('dashboard.index') }}">{{ trans('app.breadcrumb_dashboard') }}</a>
              </li>
              <li>
                <a href="{{ route('people.index') }}">{{ trans('app.breadcrumb_list_contacts') }}</a>
              </li>
              <li>
                {{ $contact->name }}
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>

    <!-- Page header -->
    @include('people._header')

    <!-- Page content -->
    <div class="main-content central-form">
      <div class="{{ Auth::user()->getFluidLayout() }}">
        <div class="row">
          <div class="col-xs-12 col-sm-6 col-sm-offset-3 col-sm-offset-3-right">
            @include('activities.form', [
              'method' => 'POST',
              'action' => route('activities.store', $contact)
            ])
          </div>
        </div>
      </div>
    </div>

  </div>
@endsection

resources/views/activities/edit.blade.php
@extends('layouts.skeleton')

@section('content')
  <div class="people-show activities">

    {{-- Breadcrumb --}}
    <div class="breadcrumb">
      <div class="{{ Auth::user()->getFluidLayout() }}">
        <div class="row">
          <div class="col-xs-12">
            <ul class="horizontal">
              <li>
                <a href="{{ route('dashboard.index') }}">{{ trans('app.breadcrumb_dashboard') }}</a>
              </li>
              <li>
                <a href="{{ route('people.index') }}">{{ trans('app.breadcrumb_list_contacts') }}</a>
              </li>
              <li>
                {{ $contact->name }}
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>

    <!-- Page header -->
    @include('people._header')

    <!-- Page content -->
    <div class="main-content central-form">
      <div class="{{ Auth::user()->getFluidLayout() }}">
        <div class="row">
          <div class="col-xs-12 col-sm-6 col-sm-offset-3 col-sm-offset-3-right">
            @include('activities.form', [
              'method' => 'PUT',
              'action' => route('activities.update', [$activity, $contact])
            ])
          </div>
        </div>
      </div>
    </div>

  </div>
@endsection

resources/views/activities/form.blade.php
<form method="POST" action="{{ $action }}">
    {{ method_field($method) }}
    {{ csrf_field() }}

    <h2>{{ trans('people.activities_add_title', ['name' => $contact->first_name]) }}</h2>

    <div class="form-group user-input">
        <label for="summary">{{ trans('people.activities_who_was_involved') }}</label>
        <input type="search" placeholder="{{ trans('people.people_search') }}" class="form-control user-input-search-input">
        <ul class="user-input-search-results"></ul>
        <br />
        <ul class="contacts">
            <ul class="contacts-list">
                @if ($contact && $method == 'POST')
                    <li class="pretty-tag"><a href="{{ route('people.show', $contact) }}">{{ $contact->first_name }} {{ $contact->last_name }}</a></li>
                    <input type="hidden" name="contacts[]" value="{{ $contact->id }}" />
                @endif
                @foreach ($activity->contacts as $contact)
                    <li class="pretty-tag"><a href="{{ route('people.show', $contact) }}">{{ $contact->first_name }} {{ $contact->last_name }}</a></li>
                    <input type="hidden" name="contacts[]" value="{{ $contact->id }}" />
                @endforeach
            </ul>
        </ul>
    </div>

    {{-- Summary --}}
    <div class="form-group{{ $errors->has('summary') ? ' has-error' : '' }}">
        <label for="summary">{{ trans('people.activities_summary') }}</label>
        <input type="text" id="summary" class="form-control" name="summary" autofocus required maxlength="254" value="{{ old('summary') ?? $activity->summary }}">
        @if ($errors->has('summary'))
            <span class="help-block">
                <strong>{{ $errors->first('summary') }}</strong>
            </span>
        @endif
    </div>

    {{-- Date --}}
    <div class="form-group{{ $errors->has('date_it_happened') ? ' has-error' : '' }}">
        <label for="date_it_happened">{{ trans('people.activities_add_date_occured') }}</label>
        <input type="date" id="date_it_happened" name="date_it_happened" class="form-control"
               value="{{ old('date_it_happened') ?? (! is_null($activity->date_it_happened) ? $activity->date_it_happened->toDateString() : now(\App\Helpers\DateHelper::getTimezone())->toDateString()) }}"
               min="{{ now(\App\Helpers\DateHelper::getTimezone())->subYears(10)->toDateString() }}"
               max="{{ now(\App\Helpers\DateHelper::getTimezone())->toDateString() }}"
        >
        @if ($errors->has('date_it_happened'))
            <span class="help-block">
                <strong>{{ $errors->first('date_it_happened') }}</strong>
            </span>
        @endif
    </div>

    {{-- Build the Activity types dropdown --}}
    <div class="form-group{{ $errors->has('activity_type_id') ? ' has-error' : '' }}">
        <label for="activity_type_id">{{ trans('people.activities_add_pick_activity') }}</label>
        <select id="activity_type_id" name="activity_type_id" class="form-control">

            {{-- Blank option --}}
            <option value="" selected>
                -
            </option>

            {{-- Predefined options --}}
            @foreach (auth()->user()->account->activityTypeCategories as $activityTypeCategory)
                <optgroup label="{{ $activityTypeCategory->name }}">
                    @foreach (App\Models\Contact\ActivityType::where('activity_type_category_id', $activityTypeCategory->id)->get() as $activityType)
                        @if (! is_null($activity->type) && $activity->type->id == $activityType->id)
                            <option value="{{ $activityType->id }}" selected>
                                {{ $activityType->name }}
                            </option>
                        @else
                            <option value="{{ $activityType->id }}">
                                {{ $activityType->name }}
                            </option>
                        @endif
                    @endforeach
                </optgroup>
            @endforeach
        </select>
        @if ($errors->has('activity_type_id'))
            <span class="help-block">
                <strong>{{ $errors->first('activity_type_id') }}</strong>
            </span>
        @endif
    </div>

    <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
        <label for="description">{{ trans('people.activities_add_optional_comment') }}</label>
        <textarea class="form-control" id="description" name="description" rows="3">{{ old('description') ?? $activity->description }}</textarea>
        @if ($errors->has('description'))
            <span class="help-block">
                <strong>{{ $errors->first('description') }}</strong>
            </span>
        @endif
    </div>

    <div class="form-group actions">
        <button type="submit" cy-name="save-activity-button" class="btn btn-primary">{{ trans('people.activities_add_cta') }}</button>
        <a href="{{ route('people.show', $contact) }}" class="btn btn-secondary">{{ trans('app.cancel') }}</a>
    </div>
</form>

resources/views/activities/index.blade.php
<div class="col-xs-12 section-title">
  <img src="/img/people/activities.svg" class="icon-section icon-activities">
  <h3>
    {{ trans('people.section_personal_activities') }}

    <span class="{{ htmldir() == 'ltr' ? 'fr' : 'fl' }}">
      <a href="{{ route('activities.add', $contact) }}" cy-name="add-activity-button" class="btn">{{ trans('people.activities_add_activity') }}</a>
    </span>
  </h3>
</div>

@if ($contact->activities->count() == 0)

  <div class="col-xs-12" cy-name="activities-blank-state">
    <div class="section-blank">
      <h3>{{ trans('people.activities_blank_title', ['name' => $contact->first_name]) }}</h3>
      <a href="{{ route('activities.add', $contact) }}">{{ trans('people.activities_blank_add_activity') }}</a>
    </div>
  </div>

@else

  <div class="col-xs-12 activities-list">

    <ul class="table">
      @foreach($contact->activities as $activity)
      <li class="table-row" cy-name="activity-body-{{ $activity->id }}">
        <div class="table-cell date">
          {{ \App\Helpers\DateHelper::getShortDate($activity->date_it_happened) }}
        </div>
        <div class="table-cell">
          {{ $activity->getSummary() }}
        </div>
        <div class="table-cell list-actions">
            <a href="#activity{{$activity->id}}Modal" cy-name="view-activity-button-{{ $activity->id }}" data-toggle="modal">
              <i class="fa fa-eye" aria-hidden="true"></i>
            </a>
          <a href="{{ route('activities.edit', [$activity, $contact]) }}" cy-name="edit-activity-button-{{ $activity->id }}" class="edit">
            <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
          </a>
          <a href="{{ route('people.show', $contact) }}" cy-name="delete-activity-button-{{ $activity->id }}" onclick="if (confirm('{{ trans('people.activities_delete_confirmation') }}')) { $(this).closest('.table-row').find('.entry-delete-form').submit(); } return false;">
            <i class="fa fa-trash-o" aria-hidden="true"></i>
          </a>
        </div>

        <form method="POST" action="{{ route('activities.delete', [$activity, $contact]) }}" class="entry-delete-form hidden">
          {{ method_field('DELETE') }}
          {{ csrf_field() }}
        </form>
      </li>

      @endforeach
    </ul>

    @if ($contact->activities->count() != 0)
    <p class="tc">📗 <a href="{{ route('people.activities.index', $contact) }}">{{ trans('people.activities_view_activities_report') }}</a></p>
    @endif
  </div>
  @foreach($contact->activities as $activity)

      @include('people.modal.activity_view')

  @endforeach
@endif